### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by untzag** [Tyler314/led_matrix#2]
every project needs good version tracking

I strongly prefer [semantic versioning](http://semver.org/)

I like to put the version in a top-level `VERSION` file---the version can then be read from that file by other parts of the program

if this is agreeable we should begin versioning ASAP

**Comment by tyler314** [comment]
I'm not familiar with versioning at all, will you please educate me?

**Comment by tyler314** [comment]
I don't know much about this at all, thus have no preference. You have far more experience than I do using git with larger teams, so I am fine using your methods for versioning.
